#pragma once

#include "algosim/domain/carbon.hpp"
#include "algosim/domain/datacenter.hpp"
#include "algosim/domain/workload.hpp"

#include <chrono>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

namespace algosim::scenario {

// Inter-DC network profile applied by the platform generator.
// Defaults reproduce the historical hardcoded behaviour (1 Gbps links,
// latency = max(1, dist_deg * 0.5) ms).
struct NetworkProfile {
    double inter_dc_bw_mbps        = 1000.0;
    double inter_dc_latency_factor = 1.0;
};

// Fully materialized, runnable description of an experiment.
//
// Built by ScenarioBuilder from a YAML config. Self-contained: every field
// the runner or backend needs is present, and the `events` vector is the
// deterministic result of seeding the workload generator with `seed`.
struct ScenarioSpec {
    std::string                   name;
    std::string                   source_config_path;
    double                        duration_seconds           = 0.0;
    double                        dt_seconds                 = 60.0;
    double                        migration_interval_seconds = 600.0;
    int                           carbon_forecast_hours      = 0;
    std::uint64_t                 seed                       = 0;
    std::chrono::system_clock::time_point start_datetime{};

    std::vector<domain::Datacenter>    datacenters;
    std::vector<domain::WorkloadEvent> events;

    // series_id -> carbon trace
    std::unordered_map<std::string, domain::CarbonIntensitySeries> carbon_series;

    NetworkProfile network;

    // Path to the SimGrid platform XML that describes this topology.
    // Either declared directly in YAML or generated by ScenarioBuilder.
    std::string platform_xml_path;
};

}  // namespace algosim::scenario
